### Makefile -- Mixins

# Mixture (https://github.com/michipili/mixture)
# This file is part of Mixture
#
# Copyright © 2013–2015 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

LIBRARY=		mixture

SRCS+=			mixture_Format.ml
SRCS+=			mixture_Parse.ml
SRCS+=			mixture_Compare.ml
SRCS+=			mixture_Monad.ml
SRCS+=			mixture_FoldRight.ml
SRCS+=			mixture_FoldAssoc.ml
SRCS+=			mixture_NumericalFunction.ml

.include "ocaml.lib.mk"

### End of file `Makefile'
